# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1farvCChG_pJwKSctf3vaxlFhsT1in_xN
"""

list1=range(10)
print(list1)

print(list(list1))

list2=range(-4,5)
print(list(list2))

list4=range(-4,6,2)
print(list(list4))

for n in range(5):
  print(n)

for n in range(10):
    print(n, end='$$')

    #print(n, end='$')

mysum = 0

for n in range(5):
  mysum += n
  print(mysum)

mysum = 0

for n in range(5):
  mysum += n

print(mysum)

total = i = 1

n = int(input("請輸入正整數 n 的值：")) # 再問一次:為什麼要加

while(i<=n):
    total *= i  
    i+=1      

print("%d!=%d" % (n, total))

fruits = ["香蕉","蘋果","橘子","鳳梨","西瓜"]

while True:
    fruit = input("請輸入喜歡的水果(Enter 結束)：")

  # 要執行程式請記得把底下兩行 # 去除 
  #  if (fruit==""):
    break

    n = fruits.count(fruit) 
    if (n>0):  # 串列元素存在
        p=fruits.index(fruit)
        print("%s 在串列中的第 %d 項" %(fruit,p+1))
    else:
        print(fruit,"不在串列中!")

n = int(input("請輸入正整數："))

for i in range(1, n+1):
    if i % 5 ==0:
        continue
    print(i,end=" ")